spring:
  application:
    name: eureka-server

server:
  port: 8002

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka
  client:          #这个配置是集群互相获取注册信息的配置。
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
